### ISSUE TITLE
Build failed due to incorrect extension name of a JSX file

### ISSUE THREAD

**Issue by brendan-lee** [recogito/recogito-client-core#83]
Hi, I'm using Annotorious 2.5.6 in my project, but it was failed to build with Vite, showing such an error:

```
 > node_modules/@recogito/recogito-client-core/src/i18n/index.js:107:4: error: Unexpected "<"
    107 │     <TimeAgo 
        ╵     ^

error when starting dev server:
Error: Build failed with 1 error:
node_modules/@recogito/recogito-client-core/src/i18n/index.js:107:4: error: Unexpected "<"
    at failureErrorWithLog (/.../node_modules/esbuild/lib/main.js:1493:15)
    at /.../node_modules/esbuild/lib/main.js:1151:28
    at runOnEndCallbacks (/.../node_modules/esbuild/lib/main.js:941:63)
    at buildResponseToResult (/.../node_modules/esbuild/lib/main.js:1149:7)
    at /.../node_modules/esbuild/lib/main.js:1258:14
    at /.../node_modules/esbuild/lib/main.js:629:9
    at handleIncomingPacket (/.../node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/.../node_modules/esbuild/lib/main.js:596:7)
    at Socket.emit (events.js:376:20)
    at addChunk (internal/streams/readable.js:309:12)
```

Looks like `/src/i18n/index.js` should ends with '.jsx' so that Vite can build it properly

**Comment by rsimon** [comment]
Ah, good point! Yes that's true, sorry - and thanks for reporting. Vite requires jsx extensions on all source files that include JSX syntax. (The TimeAgo component is a recent addition, for v2.5.7. I.e. it looks like you are actually ahead of v2.5.6, on latest main.)

**Comment by brendan-lee** [comment]
Yes, it's v2.5.7 actually. Thank you for your work! 👍
